services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trainservice'
      - 'POSTGRES_PASSWORD=QWEasd123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'